---
title: "Exam in R for data science - Group 12"
format: revealjs
---

## **Introduction**

### **Group 12:**

s132347 (Sofie Emilie Hagelund)\
s253710 (Henrique Gomes)\
s253689 (Paula Meer Janssen)\
s252750 (Shuyue Zhang)\
s253719 (Eszter Hudra)

### Chosen dataset: 

#### Analysis of Breast Cancer Dataset

-   MAQC-II Project: human breast cancer (BR) dataset

------------------------------------------------------------------------

## Materials and Methods

#### Description and use of the Dataset

-   **Age**
-   **Race**
-   **pCR vs RD (response to treatment)**
    -   pCR = pathological complete response (=good)

    -   RD = residual disease (=bad)
-   **Treatment(s)**

---

## Materials and Methods (continued)

#### Tumor categories:

-   **Tumor (0-4) size before treatment**
    -   The higher, the bigger the size
-   **Lymph node (0-3) involvement before treatment**
    -   The higher, the more lymph node involvement
-   **Grade/Level of aggressiveness (1-3)**
    -   The higher the more aggressive

---

## Materials and Methods (continued)

#### Brush-up on receptor genotype descripton:

-   **Receptor status** (+/-)
    -   Receptor positive (+) = better prognosis
    -   Receptor negative (-) = worse prognosis
    -   Receptors status:
        -   Estrogen
        -   Progesterone
        -   HER2

------------------------------------------------------------------------

## Demographics - Age and Race

\*\* INSERT GRAPH 04 \*\*

-   Breast cancer patients are mainly white and between the ages of 40-59.

------------------------------------------------------------------------

## Age and Genotype

\*\* INSERT GRAPH 23 \*\*

-   **The most common Genotype trend is**
    -   ER+, PR+, HER2-
    -   ER-, PR-, HER2- (Triple negative)

There is [no clear]{.underline} correlation between age and genotype.

------------------------------------------------------------------------

## Aim #1

*Do the theoretically predicted prognoses for the genotypes match the observed responses in the dataset?*

------------------------------------------------------------------------

## ER+ patients have the worst treatment response

\*\* INSERT GRAPH 18 \*\*

**Surprisingly**:

-   ER+ patients have the worst treatment response.

-   HER+ only patients and triple-negative patients have the best treatment response.

------------------------------------------------------------------------

## Aim #2

*Does the treatment response from the genotypes correlate with tumor aggressiveness, size, and lymph node involvement?*

------------------------------------------------------------------------

## Treatment response does not correlate with tumor aggressiveness

\*\* INSERT GRAPH 19 \*\*

-   Even though being ER+ does have the worst response, they do not have a more aggressive tumor grade.

-   Being ER-, PR- leads to a more aggressive tumor grade, even though they had the best response.

------------------------------------------------------------------------

## Treatment response does not correlate with tumor size

\*\* INSERT GRAPH 20 \*\*

-   Most of the genotypes have a tumor size 2, or have developed into size 3-4. Especially the case for:

    -   ER+ genotype

    -   ER-, PR- genotype combinations.

------------------------------------------------------------------------

## Treatment response does not correlate with lymph node involvement

\*\* INSERT GRAPH 21 \*\*

Generally, it seems that following genotypes have most lymph node involvement:

-   ER+, PR-, HER2-

-   ER-,PR-, HER2+

-   ER-, PR-, HER2- (triple negative)

------------------------------------------------------------------------

## Aim #3

*Does the response and treatment type give any insights into whether a specific treatment is favorable for certain genotypes?*

------------------------------------------------------------------------

## More treatment options leads to better response

\*\* INSERT GRAPH 22 \*\*

-   The last two groups were exposed to most different treatment options:

    -   ER-,PR-, HER2+

    -   ER-, PR-, HER2- (triple negative)

<!-- -->

-   A general broad TFAC and TFEC is not working for ER+ patients.

------------------------------------------------------------------------

## Conclusion/Discussion

-   More personalized treatment options give better response.

-   The level of aggressiveness, tumor size, and lymph node involvement do not necessarily mean a bad response if personalized treatment is an option.

------------------------------------------------------------------------

# Thank you for your Attention

We are happy to answer any of your questions!
