---
title: "00_all" 
format: html 
editor: visual 
---

# Master Document

## Full list of all analysis we created

Barplots of Henrique:

-   05 E and P receptor statuses vs cancer aggressiveness

-   06 HER2 receptor status vs cancer aggressiveness

-   07 HER2 receptor status vs tumor size before treatment

-   08 HER2 receptor status vs nodes before treatment

-   09 E and P receptor statuses vs treatment outcome

-   10 HER2 receptor status vs treatment outcome

-   11 Cancer aggressiveness vs treatment outcome

Main plots of Paula and Sylvia:

-   12 - Age vs. Outcome

-   13 - Age and Race vs. Aggressivness and Tumor Size

-   14 - Tumorsize, Lymphnodes and Aggression Comparison

-   15 - Response to Treatment according to Receptor Status

-   16 - Her2 fish vs. Her2 receptor positive or negative and linear regression of her2 and tumor size

-   17 - PCA with colouring according to receptor positiveness or negativeness

Final plots of Sofie:

-   18 (Response (pCR vs RD) by ER/PR/HER2 Genotypes)

-   19 (Tumor Grade (1–3) by ER/PR/HER2 Genotypes)

-   20 (Tumor Size Before Treatment by ER/PR/HER2 Genotypes)

-   21 (Lymph Node Status Before Treatment by ER/PR/HER2 Genotypes)

-   22 (Treatment Distribution Across ER/PR/HER2 Genotypes)

## What to include:

script 04, 23, 18,*19, 20, 21, 22*

## Presentation:

1.  **Introduction (HEADLINE) - Slide 1**

    Group name (12), original topic (Oncology)

2.  **Materials and Methods (HEADLINE) - Slide 2**

    -   Presenting the dataset
    -   What is the description/meaning of the dataset
        -   List of the observations we are working with
    -   **Slide 3**: Quick background brush-up on the genotypes.
    -   **Slide 4** SHOWING ***graph 04*** - HEADLINE (Age and race)
        -   Breast cancer patients are mainly white and in the ages between 40-59.
    -   Demographics (*graph 23*) - age and genotypes

3.  **Aims**

    -   **Slide 5** - Does the theoretically predicted prognosis for specific genotypes match the observed response data

    -   **Slide 6** - *graph 18*

    -   **Slide 7** - Does the response correlate with tumor aggressiveness, tumor size, and the number of affected lymph nodes?

    -   **Slide 8, 9, 10** - *graphs 19, 20, and 21*

    -   **Slide 11** - Does the response and the treatment give any insights into whether personalized treatment is the way to go?

    -   **Slide 12** - *graph 22*

    -   **Slide 13** - Thank you for your attention.
