---
title: "04_describe"
format: html
editor: visual
---

## Load Libraries

```{r}
#| message: false
library("tidyverse")
library("here")
library("RColorBrewer")
```

## Load Data

load the data as a variable to use in descriptive graphs

```{r}
#| message: false
augment_data <- 
  read_tsv(file = here("data/03_dat_aug.tsv"))
```

## Descriptive Graphs

```{r}
custom_palette <- c(
  "#7f3667",
  "#a53e76",
  "#bb437e",
  "#d24787",
  "#e44b8d",
  "#e2619f",
  "#e27bb1",
  "#e5a0c6",
  "lightblue",
  "#B3D84C",  
  "#A6D15A",  
  "#90C84C",  
  "#70B83F",  
  "#4F9A2F",  
  "#2F7B1F",  
  "#1D6510",  
  "#004400" 
)
```

### Distribution of age groups and race

```{r}
df_plot1 <- augment_data |>
  mutate(age_group = cut(age,
                         breaks = seq(0, 100, by = 10),
                         labels = paste(seq(0, 90, 10),
                                        seq(9, 99, 10),
                                        sep = "-"))
         ) |>
  filter(!is.na(age_group)) |>
  count(age_group,
        race)

plot1_pallete <- c("#e44b8d", "#e5a0c6", "lightblue", "#B3D84C", "#70B83F")

ggplot(df_plot1,
       aes(x = age_group,
           y = n,
           fill = race)) +
  geom_col(position = "stack") +
  labs(title = "Distribution of age groups and race") +
  scale_fill_manual(values = plot1_pallete) +
  theme_bw()
```

### Distribution of hormones in different patients

```{r}
df_plot2 <- augment_data |>
  mutate(receptor_group = case_when(
    er_status == "N" & pr_status == "N" & her2_status == "N" ~ "ER-PR-HER2-",
    er_status == "P" & pr_status == "N" & her2_status == "N" ~ "ER+PR-HER2-",
    er_status == "N" & pr_status == "P" & her2_status == "N" ~ "ER-PR+HER2-",
    er_status == "N" & pr_status == "N" & her2_status == "P" ~ "ER-PR-HER2+",
    er_status == "P" & pr_status == "P" & her2_status == "N" ~ "ER+PR+HER2-",
    er_status == "P" & pr_status == "N" & her2_status == "P" ~ "ER+PR-HER2+",
    er_status == "N" & pr_status == "P" & her2_status == "P" ~ "ER-PR-HER2-",
    er_status == "P" & pr_status == "P" & her2_status == "P" ~ "ER+PR+HER2+")
    ) |>
  count(receptor_group)

plot2_palette <- c("#bb437e", "#e44b8d", "#e27bb1", "lightblue", "#A6D15A", "#70B83F", "#2F7B1F")

ggplot(df_plot2,
       aes(x = receptor_group,
           y = n,
           fill = receptor_group)) +
  geom_col() +
  labs(title = "Distribution of hormones") +
  scale_fill_manual(values = plot2_palette) +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 30,
                                   hjust = 0.5,
                                   vjust = 1))
```

### Distribution of successful or unsuccessful treatment

```{r}
df_plot3 <- augment_data |>
  filter(!is.na(response)) |>
  count(response)

plot3_palette <- c("#e27bb1", "#A6D15A")

ggplot(df_plot3,
       aes(x = response, 
           y = n,
           fill = response)) +
  geom_col() +
  labs(title = "Distribution of treatment success: 
       pCR = 'no detectable tumor after treatment'
       or RD = 'tumor remains after therapy'") +
  scale_fill_manual(values = plot3_palette) +
  theme_minimal()
```

### Distribution of tumor subtypes (histology)

```{r}
df_plot4 <- augment_data |>
  filter(!is.na(histology)) |>
  count(histology)

ggplot(df_plot4,
       aes(x = histology, 
           y = n,
           fill = histology)) +
  geom_col() +
  labs(title = "Distribution of tumor subtypes (histology)") +
  scale_fill_manual(values = custom_palette) +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   vjust = 1)) + 
  guides(fill = guide_legend(ncol = 2))
```

### Distribution of tumor aggressiveness (bmngrd = Bloom–Richardson (BR) grade)

```{r}
df_plot5 <- augment_data |>
  mutate(grade = factor(grade)) |>
  count(grade)

plot5_palette <- c("#e27bb1", "lightblue", "#A6D15A")

ggplot(df_plot5,
       aes(x = grade, 
           y = n,
           fill = grade)) +
  geom_col() +
  labs(title = "Distribution of tumor aggressiveness (BR grade)") +
  scale_fill_manual(values = plot5_palette, na.value = "gray") +
  theme_minimal()
```
