---
title: "06_analysis_2"
format: html
editor: visual
---

## Loading Libraries

```{r}
#| message: false library(here) library(tidyverse)
```

## Reading the Data

```{r}
#| message: false 
data_path <- "data/03_dat_aug.tsv"  

dataset <- read_tsv(file = here(data_path))
```

## Data Wrangling

```{r}
dataset <- dataset |>
  mutate(
    # making grade into a factor -> needed for coloring in graphs
    grade = factor(grade, levels = c(1, 2, 3), exclude = NULL)
    )
```

## Plotting

### HER2 vs Aggressiveness

```{r}
her2_vs_grade <- ggplot(dataset, aes(x = her2_status, fill = grade)) +
  geom_bar(stat = "count", position = "stack") +
  scale_fill_manual(
    values = c("1" = "pink", 
               "2" = "red", 
               "3" = "darkred", 
               "NA" = "gray")
    ) +
  labs(title = "HER2 Status vs Aggressiveness",
       x = "HER2 Status", 
       y = "Amount", 
       fill = "Grade") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

her2_vs_grade
```
