---
title: "08_analysis_4"
format: 
  html:
    self-contained: true
editor: visual
---

## Loading Libraries

```{r}
#| message: false  
library("here")  
library("tidyverse")
```

## Reading the Data

```{r}
#| message: false
data_path <- "data/03_dat_aug.tsv"    
dataset <- read_tsv(file = here(data_path))
```

## Data Wrangling

```{r}
dataset <- dataset |>   
  mutate(     
    # making nodes_before into a factor -> needed for coloring in graphs
    nodes_before = factor(
      nodes_before,
      levels = c(0, 1, 2, 3), 
      exclude = NULL))
```

## Plotting

### HER2 vs Nodes

```{r}
her2_vs_nodes <- ggplot(
  dataset, 
  aes(
    x = her2_status, 
    fill = nodes_before)) +
  geom_bar(stat = "count", 
           position = "stack") +
  scale_fill_manual(
    values = c("0" = "#90EE90",
               "1" = "#32CD32", 
               "2" = "#228B22", 
               "3" = "#006400",
               "NA" = "gray")) +
  labs(
    title = "HER2 Status vs Node Spread Before Treatment",
    x = "HER2 Status", 
    y = "Amount", 
    fill = "Node Spread") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1),
        plot.title = element_text(hjust = 0.5))

her2_vs_nodes
```
