---
title: "09_analysis_6"
format: html
---

## Load Libraries

```{r}
#| message: false
library(tidyverse)
```

## Load Data into variable

```{r}
#| message: false
augment_data <- read_tsv("/net/pupil1/home/people/s253689/projects/group_12_project/data/03_dat_aug.tsv")
```

## Tumorsize, Lymphnodes and Aggression Comparison

```{r}
ggplot(augment_data, 
       aes(x = tumor_size_before, 
           y = nodes_before, color = grade)) +
  geom_jitter(width = 0.2, height = 0.2, size = 3) +
  theme_minimal() +
  labs(title = "Tumor size vs. Lymphnodes and Aggression of Tumor",
       x = "Tumor Sizw",
       y = "Lymphnodes") 
```

```{r}
augment_data |>
  count(tumor_size_before, nodes_before, grade) |>
  ggplot(aes(x = tumor_size_before, y = nodes_before, fill = n)) +
  geom_tile(color = "white") +
  facet_wrap(~grade) +
  theme_minimal() +
  labs(title = "HAmount of Tumor Sizes and Lymphnodes according to Aggression",
       x = "Tumorsize",
       y = "Lymphnodes",
       fill = "Amount")
```
