---
title: "11_analysis_7"
format: 
  html:
    self-contained: true
editor: visual
---

## Loading Libraries

```{r}
#| message: false 
library("here") 
library("tidyverse")
source(here("R/99_proj_func.R"))
```

## Reading the Data

```{r}
#| message: false
data_path <- "data/03_dat_aug.tsv"
dataset <- read_tsv(file = here(data_path))
```

## Data Wrangling

```{r}
dataset <- dataset |>      
  mutate(          
    # making grade and response into factors 
    # -> for coloring graphs and separating NAs in grade
    grade = factor(
      grade,
      levels = c(1, 2, 3),
      exclude = NULL),
    response = factor(
      response,
      levels = c("RD", "pCR"), 
      exclude = NULL))
```

## Plotting

### Aggressiveness vs Treatment Outcome

```{r}
grade_vs_outcome <- ggplot(
  dataset, 
  aes(
    x = grade, 
    fill = response)) +
  geom_bar(stat = "count",
           position = "stack") +
  scale_fill_manual(
    values = c("RD" = "darkred", 
               "pCR" = "#32CD32")) +
  labs(
    title = "Aggressiveness vs Treatment Outcome",
    x = "Grade", 
    y = "Amount", 
    fill = "Response") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1),
        plot.title = element_text(hjust = 0.5))

grade_vs_outcome
```

### Save plot

```{r}
save_plot(grade_vs_outcome, 
          "11_plot_7.png")
```
