---
title: "12_analysis_9"
format: html
---

## Load Libraries

```{r}
#| message: false
library(tidyverse)
```

## Load Data

```{r}
#| message: false
augment_data <- read_tsv("/net/pupil1/home/people/s253689/projects/group_12_project/data/03_dat_aug.tsv")
```

## PCA

```{r}
df_clean <- augment_data |>
  select(her2_num, er_num, pr_num, age) |>
  drop_na()

df_scaled <- df_clean |>
  map_dfc(~ (. - mean(.)) / sd(.))

pca_res <- prcomp(df_scaled, center = FALSE, scale. = FALSE)

pca_df <- as_tibble(pca_res$x) |>
  bind_cols(df_clean)

pca_df |>
  ggplot(aes(x = PC1, y = PC2, color = factor(er_num))) +
  geom_point(size = 3, alpha = 0.7) +
  labs(color = "ER Status") +
  theme_minimal()

pca_df |>
  ggplot(aes(x = PC1, y = PC2, color = factor(pr_num))) +
  geom_point(size = 3, alpha = 0.7) +
  labs(color = "PR Status") +
  theme_minimal()

pca_df |>
  ggplot(aes(x = PC1, y = PC2, color = factor(her2_num))) +
  geom_point(size = 3, alpha = 0.7) +
  labs(color = "HER2 Status") +
  theme_minimal()


```
