---
title: "Graphs_Sylvia"
format: html
---

## Load libraries

```{r}
#| message: false
library(here)
library(tidyverse)
```

## Load augment data

```{r}
#| message: false
input_file <- here("data/03_dat_aug.tsv")
dat_aug <- read_tsv(
  input_file,
  na = c("", "NA"),
  show_col_types = FALSE)
```

## Age and race compared to aggressiveness

```{r}
dat_aug |> 
  filter(!is.na(grade), !is.na(age))|> 
  ggplot(aes(x = factor(grade), y = age)) +
  geom_boxplot(alpha = 0.6, outlier.shape = NA) +
  geom_jitter(aes(color = race),
              width = 0.2, alpha = 0.7, size = 1) +
  labs(
    title = "Age vs Tumor Grade",
    x = "Tumor Grade",
    y = "Age"
  ) +
  theme_minimal()

```

## Age v.s. Tumor Size

```{r}
dat_aug |> 
  filter(!is.na(age), !is.na(tumor_size_before), tumor_size_before != 0)|> 
  ggplot(
    aes(x = factor(tumor_size_before), y = age)) +
    geom_boxplot(alpha = 0.6, outlier.shape = NA) +
    geom_jitter(width = 0.15, alpha = 0.7, size = 1.5) +
  labs(
    title = "Age vs Tumor Size",
    x = "Tumor Size (before treatment)",
    y = "Age"
  ) +
  theme_minimal(base_size = 14)



```

## Hormone Receptor Status vs Aggressiveness

```{r}
dat_aug |>
  filter(!is.na(grade)) |>
  group_by(hormone_group) |>
  ggplot(aes(x = hormone_group, fill = factor(grade))) +
  geom_bar(position = "fill") + 
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(
    values = c(
      "1" = "pink", 
      "2" = "red", 
      "3" = "darkred"
      )) +
  labs(
    title = "Hormone Receptor Status vs Tumor Grade (Proportion)",
    x = "Hormone Receptor Status Combination",
    y = "Proportion (%)",
    fill = "Grade"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

## HER2 vs Aggressiveness

```{r}
dat_aug |> 
  filter(!is.na(grade), !is.na(her2_status)) |>
  ggplot(aes(x = her2_status, fill = factor(grade))) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(
    values = c("1" = "pink", 
               "2" = "red", 
               "3" = "darkred")
  ) +
  labs(title = "HER2 Status vs Aggressiveness (Proportion)",
       x = "HER2 Status", 
       y = "Proportion (%)", 
       fill = "Grade") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## HER2 vs Tumor Size Before Treatment

```{r}
dat_aug |> 
  filter(!is.na(tumor_size_before)) |> 
  ggplot(aes(x = her2_status, fill = factor(tumor_size_before))) +
  geom_bar(position = "fill") + 
  scale_y_continuous(labels = scales::percent_format()) + 
  scale_fill_manual(
    values = c("0" = "#ADD8E6",
               "1" = "#87CEFA", 
               "2" = "#4682B4", 
               "3" = "#0000CD",
               "4" = "#00008B")
  ) +
  labs(title = "HER2 Status vs Tumor Size Before Treatment",
       x = "HER2 Status", 
       y = "Proportion (%)", 
       fill = "Tumor Size") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## HER2 vs Node Spread

```{r}
dat_aug |> 
  filter(!is.na(nodes_before)) |>
  ggplot(aes(x = her2_status, fill = factor(nodes_before))) +
  geom_bar(position = "fill") +  
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(
    values = c("0" = "#90EE90",
               "1" = "#32CD32", 
               "2" = "#228B22", 
               "3" = "#006400")
  ) +
  labs(title = "HER2 Status vs Node Spread Before Treatment (Proportion)",
       x = "HER2 Status", 
       y = "Proportion (%)", 
       fill = "Node Spread") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Hormone Receptor vs Treatment Outcome

```{r}
dat_aug |> 
  filter(!is.na(hormone_group)) |>
  ggplot(aes(x = hormone_group, fill = response)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(
    values = c("RD" = "darkred", "pCR" = "#32CD32")
  ) +
  labs(title = "ER & PR Status vs Treatment Outcome (Proportion)",
       x = "Receptor Status Combination", 
       y = "Proportion (%)", 
       fill = "Response") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
