---
title: "Bar plots"
format: html
editor: visual
---

## Loading Libraries

```{r}
library(tidyverse)
library(here)
library(patchwork)
```

## Reading the Data

```{r}
data_path <- "data/03_dat_aug.tsv"

dataset <- read_tsv(file = here(data_path))
```

```{r}
dataset
```

## Data Wrangling

```{r}
dataset <- dataset |>
  mutate(
    # creating a new column for the combinations of E and P receptor statuses
    er_pr_status = case_when(
    er_status == "P" & pr_status == "P" ~ "ER Positive, PR Positive",
    er_status == "P" & pr_status == "N" ~ "ER Positive, PR Negative",
    er_status == "N" & pr_status == "P" ~ "ER Negative, PR Positive",
    er_status == "N" & pr_status == "N" ~ "ER Negative, PR Negative"
    ),
    # making certain variables into facotrs -> needed for coloring in graphs
    grade = factor(
      grade, levels = c(1, 2, 3), exclude = NULL
      ),
    tumor_size_before = factor(
      tumor_size_before, levels = c(0, 1, 2, 3, 4), exclude = NULL
      ),
    nodes_before = factor(
      nodes_before, levels = c(0, 1, 2, 3), exclude = NULL
    ),
    response = factor(
      response, levels = c("RD", "pCR"), exclude = NULL)
)
```

## Plotting

### ER & PR Status vs Aggressiveness

```{r}
receptors_vs_grade <- ggplot(dataset, aes(x = er_pr_status, fill = grade)) +
  geom_bar(stat = "count", position = "stack") +
  scale_fill_manual(
    values = c("1" = "pink", 
               "2" = "red", 
               "3" = "darkred", 
               "NA" = "gray")) +
  labs(title = "ER & PR Status vs Aggressiveness",
       x = "Receptor Status Combination", 
       y = "Amount", 
       fill = "Grade") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

receptors_vs_grade
```

### HER2 vs Aggressiveness

```{r}
her2_vs_grade <- ggplot(dataset, aes(x = her2_status, fill = grade)) +
  geom_bar(stat = "count", position = "stack") +
  scale_fill_manual(
    values = c("1" = "pink", 
               "2" = "red", 
               "3" = "darkred", 
               "NA" = "gray")
    ) +
  labs(title = "HER2 Status vs Aggressiveness",
       x = "HER2 Status", 
       y = "Amount", 
       fill = "Grade") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

her2_vs_grade
```

### HER2 vs Tumor Size

```{r}
her2_vs_tmrsz <- ggplot(dataset, aes(x = her2_status, fill = tumor_size_before)) +
  geom_bar(stat = "count", position = "stack") +
  scale_fill_manual(
    values = c("0" = "#ADD8E6",
               "1" = "#87CEFA", 
               "2" = "#4682B4", 
               "3" = "#0000CD",
               "4" = "#00008B",
               "NA" = "gray")
    ) +
  labs(title = "HER2 Status vs Tumor Size Before Treatment",
       x = "HER2 Status", 
       y = "Amount", 
       fill = "Tumor Size") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

her2_vs_tmrsz
```

### HER2 vs Nodes

```{r}
her2_vs_nodes <- ggplot(dataset, aes(x = her2_status, fill = nodes_before)) +
  geom_bar(stat = "count", position = "stack") +
  scale_fill_manual(
    values = c("0" = "#90EE90",
               "1" = "#32CD32", 
               "2" = "#228B22", 
               "3" = "#006400",
               "NA" = "gray")
    ) +
  labs(title = "HER2 Status vs Node Spread Before Treatment",
       x = "HER2 Status", 
       y = "Amount", 
       fill = "Node Spread") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

her2_vs_nodes
```

### ER & PR Status vs Treatment Outcome

```{r}
receptors_vs_outcome <- ggplot(dataset, aes(x = er_pr_status, fill = response)) +
  geom_bar(stat = "count", position = "stack") +
  scale_fill_manual(
    values = c("RD" = "darkred", 
               "pCR" = "#32CD32")) +
  labs(title = "ER & PR Status vs Treatment Outcome",
       x = "Receptor Status Combination", 
       y = "Amount", 
       fill = "Response") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

receptors_vs_outcome
```

### HER2 Status vs Treatment Outcome

```{r}
her2_vs_outcome <- ggplot(dataset, aes(x = her2_status, fill = response)) +
  geom_bar(stat = "count", position = "stack") +
  scale_fill_manual(
    values = c("RD" = "darkred", 
               "pCR" = "#32CD32")) +
  labs(title = "HER2 Status vs Treatment Outcome",
       x = "HER2 Status", 
       y = "Amount", 
       fill = "Response") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

her2_vs_outcome
```

### Aggressiveness vs Treatment Outcome

```{r}
grade_vs_outcome <- ggplot(dataset, aes(x = grade, fill = response)) +
  geom_bar(stat = "count", position = "stack") +
  scale_fill_manual(
    values = c("RD" = "darkred", 
               "pCR" = "#32CD32")) +
  labs(title = "Aggressiveness vs Treatment Outcome",
       x = "Grade", 
       y = "Amount", 
       fill = "Response") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

grade_vs_outcome
```
